
namespace Stok_Takip_Otomasyonu
{
    partial class FormMusteriListele
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMusteriListele));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.groupBox1 = new Guna.UI2.WinForms.Guna2GroupBox();
            this.btnGuncelle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAdres = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtTelefon = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAdSoyad = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.txtTc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.dataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnSil = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtTcAra = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.btnYazdir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.printDocument1 = new System.Drawing.Printing.PrintDocument();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.groupBox1.BorderRadius = 12;
            this.groupBox1.Controls.Add(this.btnGuncelle);
            this.groupBox1.Controls.Add(this.txtEmail);
            this.groupBox1.Controls.Add(this.txtAdres);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.txtTelefon);
            this.groupBox1.Controls.Add(this.txtAdSoyad);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.txtTc);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.groupBox1.FillColor = System.Drawing.Color.Transparent;
            this.groupBox1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.Color.White;
            this.groupBox1.Location = new System.Drawing.Point(13, 41);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(375, 523);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.Text = "Müşteri Listeleme";
            // 
            // btnGuncelle
            // 
            this.btnGuncelle.AllowAnimations = true;
            this.btnGuncelle.AllowMouseEffects = true;
            this.btnGuncelle.AllowToggling = false;
            this.btnGuncelle.AnimationSpeed = 200;
            this.btnGuncelle.AutoGenerateColors = false;
            this.btnGuncelle.AutoRoundBorders = false;
            this.btnGuncelle.AutoSizeLeftIcon = true;
            this.btnGuncelle.AutoSizeRightIcon = true;
            this.btnGuncelle.BackColor = System.Drawing.Color.Transparent;
            this.btnGuncelle.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnGuncelle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuncelle.BackgroundImage")));
            this.btnGuncelle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuncelle.ButtonText = "Güncelle";
            this.btnGuncelle.ButtonTextMarginLeft = 0;
            this.btnGuncelle.ColorContrastOnClick = 45;
            this.btnGuncelle.ColorContrastOnHover = 45;
            this.btnGuncelle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnGuncelle.CustomizableEdges = borderEdges4;
            this.btnGuncelle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuncelle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuncelle.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnGuncelle.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnGuncelle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGuncelle.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuncelle.ForeColor = System.Drawing.Color.White;
            this.btnGuncelle.IconLeft = null;
            this.btnGuncelle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuncelle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuncelle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuncelle.IconMarginLeft = 11;
            this.btnGuncelle.IconPadding = 10;
            this.btnGuncelle.IconRight = null;
            this.btnGuncelle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuncelle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuncelle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuncelle.IconSize = 25;
            this.btnGuncelle.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnGuncelle.IdleBorderRadius = 0;
            this.btnGuncelle.IdleBorderThickness = 0;
            this.btnGuncelle.IdleFillColor = System.Drawing.Color.Empty;
            this.btnGuncelle.IdleIconLeftImage = null;
            this.btnGuncelle.IdleIconRightImage = null;
            this.btnGuncelle.IndicateFocus = false;
            this.btnGuncelle.Location = new System.Drawing.Point(233, 390);
            this.btnGuncelle.Name = "btnGuncelle";
            this.btnGuncelle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuncelle.OnDisabledState.BorderRadius = 30;
            this.btnGuncelle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuncelle.OnDisabledState.BorderThickness = 1;
            this.btnGuncelle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuncelle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuncelle.OnDisabledState.IconLeftImage = null;
            this.btnGuncelle.OnDisabledState.IconRightImage = null;
            this.btnGuncelle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnGuncelle.onHoverState.BorderRadius = 30;
            this.btnGuncelle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuncelle.onHoverState.BorderThickness = 1;
            this.btnGuncelle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnGuncelle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGuncelle.onHoverState.IconLeftImage = null;
            this.btnGuncelle.onHoverState.IconRightImage = null;
            this.btnGuncelle.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnGuncelle.OnIdleState.BorderRadius = 30;
            this.btnGuncelle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuncelle.OnIdleState.BorderThickness = 1;
            this.btnGuncelle.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnGuncelle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuncelle.OnIdleState.IconLeftImage = null;
            this.btnGuncelle.OnIdleState.IconRightImage = null;
            this.btnGuncelle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnGuncelle.OnPressedState.BorderRadius = 30;
            this.btnGuncelle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuncelle.OnPressedState.BorderThickness = 1;
            this.btnGuncelle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnGuncelle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuncelle.OnPressedState.IconLeftImage = null;
            this.btnGuncelle.OnPressedState.IconRightImage = null;
            this.btnGuncelle.Size = new System.Drawing.Size(122, 36);
            this.btnGuncelle.TabIndex = 6;
            this.btnGuncelle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuncelle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuncelle.TextMarginLeft = 0;
            this.btnGuncelle.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuncelle.UseDefaultRadiusAndThickness = true;
            this.btnGuncelle.Click += new System.EventHandler(this.btnGuncelle_Click);
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 10;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.ForeColor = System.Drawing.Color.Black;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 12;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(125, 330);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties28;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(230, 39);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 5;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 1;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtAdres
            // 
            this.txtAdres.AcceptsReturn = false;
            this.txtAdres.AcceptsTab = false;
            this.txtAdres.AnimationSpeed = 200;
            this.txtAdres.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAdres.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAdres.AutoSizeHeight = true;
            this.txtAdres.BackColor = System.Drawing.Color.Transparent;
            this.txtAdres.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAdres.BackgroundImage")));
            this.txtAdres.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAdres.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAdres.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAdres.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAdres.BorderRadius = 10;
            this.txtAdres.BorderThickness = 1;
            this.txtAdres.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAdres.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdres.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAdres.DefaultText = "";
            this.txtAdres.FillColor = System.Drawing.Color.White;
            this.txtAdres.ForeColor = System.Drawing.Color.Black;
            this.txtAdres.HideSelection = true;
            this.txtAdres.IconLeft = null;
            this.txtAdres.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdres.IconPadding = 12;
            this.txtAdres.IconRight = null;
            this.txtAdres.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdres.Lines = new string[0];
            this.txtAdres.Location = new System.Drawing.Point(125, 266);
            this.txtAdres.MaxLength = 32767;
            this.txtAdres.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAdres.Modified = false;
            this.txtAdres.Multiline = false;
            this.txtAdres.Name = "txtAdres";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdres.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAdres.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdres.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Black;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdres.OnIdleState = stateProperties32;
            this.txtAdres.Padding = new System.Windows.Forms.Padding(3);
            this.txtAdres.PasswordChar = '\0';
            this.txtAdres.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAdres.PlaceholderText = "";
            this.txtAdres.ReadOnly = false;
            this.txtAdres.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAdres.SelectedText = "";
            this.txtAdres.SelectionLength = 0;
            this.txtAdres.SelectionStart = 0;
            this.txtAdres.ShortcutsEnabled = true;
            this.txtAdres.Size = new System.Drawing.Size(230, 39);
            this.txtAdres.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAdres.TabIndex = 4;
            this.txtAdres.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAdres.TextMarginBottom = 0;
            this.txtAdres.TextMarginLeft = 3;
            this.txtAdres.TextMarginTop = 1;
            this.txtAdres.TextPlaceholder = "";
            this.txtAdres.UseSystemPasswordChar = false;
            this.txtAdres.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(19, 85);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(95, 20);
            this.label1.TabIndex = 0;
            this.label1.Text = "TC Kimlik:";
            // 
            // txtTelefon
            // 
            this.txtTelefon.AcceptsReturn = false;
            this.txtTelefon.AcceptsTab = false;
            this.txtTelefon.AnimationSpeed = 200;
            this.txtTelefon.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefon.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefon.AutoSizeHeight = true;
            this.txtTelefon.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefon.BackgroundImage")));
            this.txtTelefon.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTelefon.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefon.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTelefon.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTelefon.BorderRadius = 10;
            this.txtTelefon.BorderThickness = 1;
            this.txtTelefon.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefon.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTelefon.DefaultText = "";
            this.txtTelefon.FillColor = System.Drawing.Color.White;
            this.txtTelefon.ForeColor = System.Drawing.Color.Black;
            this.txtTelefon.HideSelection = true;
            this.txtTelefon.IconLeft = null;
            this.txtTelefon.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.IconPadding = 12;
            this.txtTelefon.IconRight = null;
            this.txtTelefon.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.Lines = new string[0];
            this.txtTelefon.Location = new System.Drawing.Point(125, 203);
            this.txtTelefon.MaxLength = 32767;
            this.txtTelefon.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefon.Modified = false;
            this.txtTelefon.Multiline = false;
            this.txtTelefon.Name = "txtTelefon";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefon.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Black;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnIdleState = stateProperties36;
            this.txtTelefon.Padding = new System.Windows.Forms.Padding(3);
            this.txtTelefon.PasswordChar = '\0';
            this.txtTelefon.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefon.PlaceholderText = "";
            this.txtTelefon.ReadOnly = false;
            this.txtTelefon.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefon.SelectedText = "";
            this.txtTelefon.SelectionLength = 0;
            this.txtTelefon.SelectionStart = 0;
            this.txtTelefon.ShortcutsEnabled = true;
            this.txtTelefon.Size = new System.Drawing.Size(230, 39);
            this.txtTelefon.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefon.TabIndex = 3;
            this.txtTelefon.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefon.TextMarginBottom = 0;
            this.txtTelefon.TextMarginLeft = 3;
            this.txtTelefon.TextMarginTop = 1;
            this.txtTelefon.TextPlaceholder = "";
            this.txtTelefon.UseSystemPasswordChar = false;
            this.txtTelefon.WordWrap = true;
            // 
            // txtAdSoyad
            // 
            this.txtAdSoyad.AcceptsReturn = false;
            this.txtAdSoyad.AcceptsTab = false;
            this.txtAdSoyad.AnimationSpeed = 200;
            this.txtAdSoyad.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAdSoyad.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAdSoyad.AutoSizeHeight = true;
            this.txtAdSoyad.BackColor = System.Drawing.Color.Transparent;
            this.txtAdSoyad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAdSoyad.BackgroundImage")));
            this.txtAdSoyad.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAdSoyad.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAdSoyad.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAdSoyad.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAdSoyad.BorderRadius = 10;
            this.txtAdSoyad.BorderThickness = 1;
            this.txtAdSoyad.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAdSoyad.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdSoyad.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAdSoyad.DefaultText = "";
            this.txtAdSoyad.FillColor = System.Drawing.Color.White;
            this.txtAdSoyad.ForeColor = System.Drawing.Color.Black;
            this.txtAdSoyad.HideSelection = true;
            this.txtAdSoyad.IconLeft = null;
            this.txtAdSoyad.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdSoyad.IconPadding = 12;
            this.txtAdSoyad.IconRight = null;
            this.txtAdSoyad.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdSoyad.Lines = new string[0];
            this.txtAdSoyad.Location = new System.Drawing.Point(125, 141);
            this.txtAdSoyad.MaxLength = 32767;
            this.txtAdSoyad.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAdSoyad.Modified = false;
            this.txtAdSoyad.Multiline = false;
            this.txtAdSoyad.Name = "txtAdSoyad";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdSoyad.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAdSoyad.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdSoyad.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Black;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdSoyad.OnIdleState = stateProperties40;
            this.txtAdSoyad.Padding = new System.Windows.Forms.Padding(3);
            this.txtAdSoyad.PasswordChar = '\0';
            this.txtAdSoyad.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAdSoyad.PlaceholderText = "";
            this.txtAdSoyad.ReadOnly = false;
            this.txtAdSoyad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAdSoyad.SelectedText = "";
            this.txtAdSoyad.SelectionLength = 0;
            this.txtAdSoyad.SelectionStart = 0;
            this.txtAdSoyad.ShortcutsEnabled = true;
            this.txtAdSoyad.Size = new System.Drawing.Size(230, 39);
            this.txtAdSoyad.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAdSoyad.TabIndex = 2;
            this.txtAdSoyad.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAdSoyad.TextMarginBottom = 0;
            this.txtAdSoyad.TextMarginLeft = 3;
            this.txtAdSoyad.TextMarginTop = 1;
            this.txtAdSoyad.TextPlaceholder = "";
            this.txtAdSoyad.UseSystemPasswordChar = false;
            this.txtAdSoyad.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(19, 150);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(92, 20);
            this.label4.TabIndex = 0;
            this.label4.Text = "Ad Soyad:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(19, 212);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(76, 20);
            this.label5.TabIndex = 0;
            this.label5.Text = "Telefon:";
            // 
            // txtTc
            // 
            this.txtTc.AcceptsReturn = false;
            this.txtTc.AcceptsTab = false;
            this.txtTc.AnimationSpeed = 200;
            this.txtTc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTc.AutoSizeHeight = true;
            this.txtTc.BackColor = System.Drawing.Color.Transparent;
            this.txtTc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTc.BackgroundImage")));
            this.txtTc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTc.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTc.BorderRadius = 10;
            this.txtTc.BorderThickness = 1;
            this.txtTc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTc.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTc.DefaultText = "";
            this.txtTc.FillColor = System.Drawing.Color.White;
            this.txtTc.ForeColor = System.Drawing.Color.Black;
            this.txtTc.HideSelection = true;
            this.txtTc.IconLeft = null;
            this.txtTc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTc.IconPadding = 12;
            this.txtTc.IconRight = null;
            this.txtTc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTc.Lines = new string[0];
            this.txtTc.Location = new System.Drawing.Point(125, 77);
            this.txtTc.MaxLength = 32767;
            this.txtTc.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTc.Modified = false;
            this.txtTc.Multiline = false;
            this.txtTc.Name = "txtTc";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTc.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTc.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTc.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Black;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTc.OnIdleState = stateProperties44;
            this.txtTc.Padding = new System.Windows.Forms.Padding(3);
            this.txtTc.PasswordChar = '\0';
            this.txtTc.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTc.PlaceholderText = "";
            this.txtTc.ReadOnly = false;
            this.txtTc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTc.SelectedText = "";
            this.txtTc.SelectionLength = 0;
            this.txtTc.SelectionStart = 0;
            this.txtTc.ShortcutsEnabled = true;
            this.txtTc.Size = new System.Drawing.Size(230, 39);
            this.txtTc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTc.TabIndex = 1;
            this.txtTc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTc.TextMarginBottom = 0;
            this.txtTc.TextMarginLeft = 3;
            this.txtTc.TextMarginTop = 1;
            this.txtTc.TextPlaceholder = "";
            this.txtTc.UseSystemPasswordChar = false;
            this.txtTc.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(19, 275);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(63, 20);
            this.label6.TabIndex = 0;
            this.label6.Text = "Adres:";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(19, 338);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(65, 20);
            this.label7.TabIndex = 0;
            this.label7.Text = "E-Mail:";
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowCustomTheming = false;
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dataGridView1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.dataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridView1.BackgroundColor = System.Drawing.SystemColors.Control;
            this.dataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dataGridView1.ColumnHeadersHeight = 40;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.Name = null;
            this.dataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView1.DefaultCellStyle = dataGridViewCellStyle6;
            this.dataGridView1.EnableHeadersVisualStyles = false;
            this.dataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridView1.Location = new System.Drawing.Point(400, 62);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.RowHeadersVisible = false;
            this.dataGridView1.RowTemplate.Height = 40;
            this.dataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridView1.Size = new System.Drawing.Size(856, 498);
            this.dataGridView1.TabIndex = 39;
            this.dataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dataGridView1.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_CellDoubleClick);
            // 
            // btnSil
            // 
            this.btnSil.AllowAnimations = true;
            this.btnSil.AllowMouseEffects = true;
            this.btnSil.AllowToggling = false;
            this.btnSil.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnSil.AnimationSpeed = 200;
            this.btnSil.AutoGenerateColors = false;
            this.btnSil.AutoRoundBorders = false;
            this.btnSil.AutoSizeLeftIcon = true;
            this.btnSil.AutoSizeRightIcon = true;
            this.btnSil.BackColor = System.Drawing.Color.Transparent;
            this.btnSil.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSil.BackgroundImage")));
            this.btnSil.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.ButtonText = "Sil";
            this.btnSil.ButtonTextMarginLeft = 0;
            this.btnSil.ColorContrastOnClick = 45;
            this.btnSil.ColorContrastOnHover = 45;
            this.btnSil.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSil.CustomizableEdges = borderEdges5;
            this.btnSil.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSil.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSil.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSil.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSil.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSil.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSil.ForeColor = System.Drawing.Color.White;
            this.btnSil.IconLeft = null;
            this.btnSil.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSil.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSil.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSil.IconMarginLeft = 11;
            this.btnSil.IconPadding = 10;
            this.btnSil.IconRight = null;
            this.btnSil.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSil.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSil.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSil.IconSize = 25;
            this.btnSil.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSil.IdleBorderRadius = 0;
            this.btnSil.IdleBorderThickness = 0;
            this.btnSil.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSil.IdleIconLeftImage = null;
            this.btnSil.IdleIconRightImage = null;
            this.btnSil.IndicateFocus = false;
            this.btnSil.Location = new System.Drawing.Point(1006, 571);
            this.btnSil.Name = "btnSil";
            this.btnSil.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSil.OnDisabledState.BorderRadius = 30;
            this.btnSil.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.OnDisabledState.BorderThickness = 1;
            this.btnSil.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSil.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSil.OnDisabledState.IconLeftImage = null;
            this.btnSil.OnDisabledState.IconRightImage = null;
            this.btnSil.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnSil.onHoverState.BorderRadius = 30;
            this.btnSil.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.onHoverState.BorderThickness = 1;
            this.btnSil.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnSil.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSil.onHoverState.IconLeftImage = null;
            this.btnSil.onHoverState.IconRightImage = null;
            this.btnSil.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSil.OnIdleState.BorderRadius = 30;
            this.btnSil.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.OnIdleState.BorderThickness = 1;
            this.btnSil.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnSil.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSil.OnIdleState.IconLeftImage = null;
            this.btnSil.OnIdleState.IconRightImage = null;
            this.btnSil.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSil.OnPressedState.BorderRadius = 30;
            this.btnSil.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.OnPressedState.BorderThickness = 1;
            this.btnSil.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSil.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSil.OnPressedState.IconLeftImage = null;
            this.btnSil.OnPressedState.IconRightImage = null;
            this.btnSil.Size = new System.Drawing.Size(122, 36);
            this.btnSil.TabIndex = 7;
            this.btnSil.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSil.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSil.TextMarginLeft = 0;
            this.btnSil.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSil.UseDefaultRadiusAndThickness = true;
            this.btnSil.Click += new System.EventHandler(this.btnSil_Click);
            // 
            // txtTcAra
            // 
            this.txtTcAra.AcceptsReturn = false;
            this.txtTcAra.AcceptsTab = false;
            this.txtTcAra.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtTcAra.AnimationSpeed = 200;
            this.txtTcAra.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTcAra.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTcAra.AutoSizeHeight = true;
            this.txtTcAra.BackColor = System.Drawing.Color.Transparent;
            this.txtTcAra.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTcAra.BackgroundImage")));
            this.txtTcAra.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTcAra.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTcAra.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTcAra.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTcAra.BorderRadius = 10;
            this.txtTcAra.BorderThickness = 1;
            this.txtTcAra.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTcAra.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTcAra.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTcAra.DefaultText = "";
            this.txtTcAra.FillColor = System.Drawing.Color.White;
            this.txtTcAra.HideSelection = true;
            this.txtTcAra.IconLeft = null;
            this.txtTcAra.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTcAra.IconPadding = 12;
            this.txtTcAra.IconRight = null;
            this.txtTcAra.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTcAra.Lines = new string[0];
            this.txtTcAra.Location = new System.Drawing.Point(1046, 15);
            this.txtTcAra.MaxLength = 32767;
            this.txtTcAra.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTcAra.Modified = false;
            this.txtTcAra.Multiline = false;
            this.txtTcAra.Name = "txtTcAra";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTcAra.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTcAra.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTcAra.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTcAra.OnIdleState = stateProperties48;
            this.txtTcAra.Padding = new System.Windows.Forms.Padding(3);
            this.txtTcAra.PasswordChar = '\0';
            this.txtTcAra.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTcAra.PlaceholderText = "";
            this.txtTcAra.ReadOnly = false;
            this.txtTcAra.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTcAra.SelectedText = "";
            this.txtTcAra.SelectionLength = 0;
            this.txtTcAra.SelectionStart = 0;
            this.txtTcAra.ShortcutsEnabled = true;
            this.txtTcAra.Size = new System.Drawing.Size(210, 39);
            this.txtTcAra.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTcAra.TabIndex = 9;
            this.txtTcAra.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTcAra.TextMarginBottom = 0;
            this.txtTcAra.TextMarginLeft = 3;
            this.txtTcAra.TextMarginTop = 1;
            this.txtTcAra.TextPlaceholder = "";
            this.txtTcAra.UseSystemPasswordChar = false;
            this.txtTcAra.WordWrap = true;
            this.txtTcAra.TextChanged += new System.EventHandler(this.txtTcAra_TextChanged);
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label2.Location = new System.Drawing.Point(847, 24);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(193, 22);
            this.label2.TabIndex = 36;
            this.label2.Text = "Tc Kimlik Numarası:";
            // 
            // btnYazdir
            // 
            this.btnYazdir.AllowAnimations = true;
            this.btnYazdir.AllowMouseEffects = true;
            this.btnYazdir.AllowToggling = false;
            this.btnYazdir.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnYazdir.AnimationSpeed = 200;
            this.btnYazdir.AutoGenerateColors = false;
            this.btnYazdir.AutoRoundBorders = false;
            this.btnYazdir.AutoSizeLeftIcon = true;
            this.btnYazdir.AutoSizeRightIcon = true;
            this.btnYazdir.BackColor = System.Drawing.Color.Transparent;
            this.btnYazdir.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnYazdir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnYazdir.BackgroundImage")));
            this.btnYazdir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.ButtonText = "Yazdır";
            this.btnYazdir.ButtonTextMarginLeft = 0;
            this.btnYazdir.ColorContrastOnClick = 45;
            this.btnYazdir.ColorContrastOnHover = 45;
            this.btnYazdir.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnYazdir.CustomizableEdges = borderEdges6;
            this.btnYazdir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnYazdir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnYazdir.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnYazdir.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnYazdir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnYazdir.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnYazdir.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.IconLeft = null;
            this.btnYazdir.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnYazdir.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnYazdir.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnYazdir.IconMarginLeft = 11;
            this.btnYazdir.IconPadding = 10;
            this.btnYazdir.IconRight = null;
            this.btnYazdir.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnYazdir.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnYazdir.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnYazdir.IconSize = 25;
            this.btnYazdir.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnYazdir.IdleBorderRadius = 0;
            this.btnYazdir.IdleBorderThickness = 0;
            this.btnYazdir.IdleFillColor = System.Drawing.Color.Empty;
            this.btnYazdir.IdleIconLeftImage = null;
            this.btnYazdir.IdleIconRightImage = null;
            this.btnYazdir.IndicateFocus = false;
            this.btnYazdir.Location = new System.Drawing.Point(1134, 571);
            this.btnYazdir.Name = "btnYazdir";
            this.btnYazdir.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnYazdir.OnDisabledState.BorderRadius = 30;
            this.btnYazdir.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.OnDisabledState.BorderThickness = 1;
            this.btnYazdir.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnYazdir.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnYazdir.OnDisabledState.IconLeftImage = null;
            this.btnYazdir.OnDisabledState.IconRightImage = null;
            this.btnYazdir.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnYazdir.onHoverState.BorderRadius = 30;
            this.btnYazdir.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.onHoverState.BorderThickness = 1;
            this.btnYazdir.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnYazdir.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.onHoverState.IconLeftImage = null;
            this.btnYazdir.onHoverState.IconRightImage = null;
            this.btnYazdir.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnYazdir.OnIdleState.BorderRadius = 30;
            this.btnYazdir.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.OnIdleState.BorderThickness = 1;
            this.btnYazdir.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnYazdir.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.OnIdleState.IconLeftImage = null;
            this.btnYazdir.OnIdleState.IconRightImage = null;
            this.btnYazdir.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnYazdir.OnPressedState.BorderRadius = 30;
            this.btnYazdir.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.OnPressedState.BorderThickness = 1;
            this.btnYazdir.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnYazdir.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.OnPressedState.IconLeftImage = null;
            this.btnYazdir.OnPressedState.IconRightImage = null;
            this.btnYazdir.Size = new System.Drawing.Size(122, 36);
            this.btnYazdir.TabIndex = 8;
            this.btnYazdir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnYazdir.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnYazdir.TextMarginLeft = 0;
            this.btnYazdir.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnYazdir.UseDefaultRadiusAndThickness = true;
            this.btnYazdir.Click += new System.EventHandler(this.btnYazdir_Click);
            // 
            // printDocument1
            // 
            this.printDocument1.PrintPage += new System.Drawing.Printing.PrintPageEventHandler(this.printDocument1_PrintPage);
            // 
            // FormMusteriListele
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(33)))), ((int)(((byte)(74)))));
            this.ClientSize = new System.Drawing.Size(1268, 619);
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.btnYazdir);
            this.Controls.Add(this.btnSil);
            this.Controls.Add(this.txtTcAra);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.groupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormMusteriListele";
            this.Text = "FormMusteriListele";
            this.Load += new System.EventHandler(this.FormMusteriListele_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2GroupBox groupBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGuncelle;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtAdres;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefon;
        private Bunifu.UI.WinForms.BunifuTextBox txtAdSoyad;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txtTc;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSil;
        private Bunifu.UI.WinForms.BunifuTextBox txtTcAra;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnYazdir;
        private System.Drawing.Printing.PrintDocument printDocument1;
    }
}