
namespace Stok_Takip_Otomasyonu
{
    partial class FormUrunListele
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormUrunListele));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.comboMarka = new Guna.UI2.WinForms.Guna2ComboBox();
            this.comboKategori = new Guna.UI2.WinForms.Guna2ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.dataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnSil = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnMarkaGüncelle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnGüncelle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SatışFiyatıtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AlışFiyatıtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Miktarıtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ÜrünAdıtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Markatxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Kategoritxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BarkodNotxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.btnYazdir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.printDocument1 = new System.Drawing.Printing.PrintDocument();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // comboMarka
            // 
            this.comboMarka.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.comboMarka.BackColor = System.Drawing.Color.Transparent;
            this.comboMarka.BorderRadius = 12;
            this.comboMarka.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.comboMarka.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboMarka.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.comboMarka.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.comboMarka.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.comboMarka.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.comboMarka.ItemHeight = 30;
            this.comboMarka.Location = new System.Drawing.Point(479, 556);
            this.comboMarka.Name = "comboMarka";
            this.comboMarka.Size = new System.Drawing.Size(210, 36);
            this.comboMarka.TabIndex = 10;
            // 
            // comboKategori
            // 
            this.comboKategori.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.comboKategori.BackColor = System.Drawing.Color.Transparent;
            this.comboKategori.BorderRadius = 12;
            this.comboKategori.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.comboKategori.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboKategori.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.comboKategori.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.comboKategori.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.comboKategori.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.comboKategori.ItemHeight = 30;
            this.comboKategori.Location = new System.Drawing.Point(479, 507);
            this.comboKategori.Name = "comboKategori";
            this.comboKategori.Size = new System.Drawing.Size(210, 36);
            this.comboKategori.TabIndex = 9;
            this.comboKategori.SelectedIndexChanged += new System.EventHandler(this.comboKategori_SelectedIndexChanged);
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(358, 513);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(82, 18);
            this.label2.TabIndex = 60;
            this.label2.Text = "Kategori:";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(358, 564);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(62, 18);
            this.label3.TabIndex = 61;
            this.label3.Text = "Marka:";
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowCustomTheming = false;
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridView1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.dataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridView1.BackgroundColor = System.Drawing.SystemColors.Control;
            this.dataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridView1.ColumnHeadersHeight = 40;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.Name = null;
            this.dataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridView1.EnableHeadersVisualStyles = false;
            this.dataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridView1.Location = new System.Drawing.Point(360, 72);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.RowHeadersVisible = false;
            this.dataGridView1.RowTemplate.Height = 40;
            this.dataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridView1.Size = new System.Drawing.Size(896, 414);
            this.dataGridView1.TabIndex = 59;
            this.dataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // btnSil
            // 
            this.btnSil.AllowAnimations = true;
            this.btnSil.AllowMouseEffects = true;
            this.btnSil.AllowToggling = false;
            this.btnSil.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnSil.AnimationSpeed = 200;
            this.btnSil.AutoGenerateColors = false;
            this.btnSil.AutoRoundBorders = false;
            this.btnSil.AutoSizeLeftIcon = true;
            this.btnSil.AutoSizeRightIcon = true;
            this.btnSil.BackColor = System.Drawing.Color.Transparent;
            this.btnSil.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSil.BackgroundImage")));
            this.btnSil.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.ButtonText = "Sil";
            this.btnSil.ButtonTextMarginLeft = 0;
            this.btnSil.ColorContrastOnClick = 45;
            this.btnSil.ColorContrastOnHover = 45;
            this.btnSil.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSil.CustomizableEdges = borderEdges1;
            this.btnSil.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSil.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSil.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSil.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSil.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSil.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSil.ForeColor = System.Drawing.Color.White;
            this.btnSil.IconLeft = null;
            this.btnSil.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSil.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSil.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSil.IconMarginLeft = 11;
            this.btnSil.IconPadding = 10;
            this.btnSil.IconRight = null;
            this.btnSil.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSil.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSil.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSil.IconSize = 25;
            this.btnSil.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSil.IdleBorderRadius = 0;
            this.btnSil.IdleBorderThickness = 0;
            this.btnSil.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSil.IdleIconLeftImage = null;
            this.btnSil.IdleIconRightImage = null;
            this.btnSil.IndicateFocus = false;
            this.btnSil.Location = new System.Drawing.Point(1134, 496);
            this.btnSil.Name = "btnSil";
            this.btnSil.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSil.OnDisabledState.BorderRadius = 30;
            this.btnSil.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.OnDisabledState.BorderThickness = 1;
            this.btnSil.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSil.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSil.OnDisabledState.IconLeftImage = null;
            this.btnSil.OnDisabledState.IconRightImage = null;
            this.btnSil.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnSil.onHoverState.BorderRadius = 30;
            this.btnSil.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.onHoverState.BorderThickness = 1;
            this.btnSil.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnSil.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSil.onHoverState.IconLeftImage = null;
            this.btnSil.onHoverState.IconRightImage = null;
            this.btnSil.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSil.OnIdleState.BorderRadius = 30;
            this.btnSil.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.OnIdleState.BorderThickness = 1;
            this.btnSil.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnSil.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSil.OnIdleState.IconLeftImage = null;
            this.btnSil.OnIdleState.IconRightImage = null;
            this.btnSil.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSil.OnPressedState.BorderRadius = 30;
            this.btnSil.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSil.OnPressedState.BorderThickness = 1;
            this.btnSil.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSil.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSil.OnPressedState.IconLeftImage = null;
            this.btnSil.OnPressedState.IconRightImage = null;
            this.btnSil.Size = new System.Drawing.Size(122, 32);
            this.btnSil.TabIndex = 12;
            this.btnSil.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSil.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSil.TextMarginLeft = 0;
            this.btnSil.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSil.UseDefaultRadiusAndThickness = true;
            this.btnSil.Click += new System.EventHandler(this.btnSil_Click);
            // 
            // btnMarkaGüncelle
            // 
            this.btnMarkaGüncelle.AllowAnimations = true;
            this.btnMarkaGüncelle.AllowMouseEffects = true;
            this.btnMarkaGüncelle.AllowToggling = false;
            this.btnMarkaGüncelle.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnMarkaGüncelle.AnimationSpeed = 200;
            this.btnMarkaGüncelle.AutoGenerateColors = false;
            this.btnMarkaGüncelle.AutoRoundBorders = false;
            this.btnMarkaGüncelle.AutoSizeLeftIcon = true;
            this.btnMarkaGüncelle.AutoSizeRightIcon = true;
            this.btnMarkaGüncelle.BackColor = System.Drawing.Color.Transparent;
            this.btnMarkaGüncelle.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnMarkaGüncelle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMarkaGüncelle.BackgroundImage")));
            this.btnMarkaGüncelle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMarkaGüncelle.ButtonText = "Marka Güncelle";
            this.btnMarkaGüncelle.ButtonTextMarginLeft = 0;
            this.btnMarkaGüncelle.ColorContrastOnClick = 45;
            this.btnMarkaGüncelle.ColorContrastOnHover = 45;
            this.btnMarkaGüncelle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnMarkaGüncelle.CustomizableEdges = borderEdges2;
            this.btnMarkaGüncelle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMarkaGüncelle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMarkaGüncelle.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnMarkaGüncelle.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnMarkaGüncelle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMarkaGüncelle.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMarkaGüncelle.ForeColor = System.Drawing.Color.White;
            this.btnMarkaGüncelle.IconLeft = null;
            this.btnMarkaGüncelle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMarkaGüncelle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMarkaGüncelle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnMarkaGüncelle.IconMarginLeft = 11;
            this.btnMarkaGüncelle.IconPadding = 10;
            this.btnMarkaGüncelle.IconRight = null;
            this.btnMarkaGüncelle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMarkaGüncelle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMarkaGüncelle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMarkaGüncelle.IconSize = 25;
            this.btnMarkaGüncelle.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnMarkaGüncelle.IdleBorderRadius = 0;
            this.btnMarkaGüncelle.IdleBorderThickness = 0;
            this.btnMarkaGüncelle.IdleFillColor = System.Drawing.Color.Empty;
            this.btnMarkaGüncelle.IdleIconLeftImage = null;
            this.btnMarkaGüncelle.IdleIconRightImage = null;
            this.btnMarkaGüncelle.IndicateFocus = false;
            this.btnMarkaGüncelle.Location = new System.Drawing.Point(704, 528);
            this.btnMarkaGüncelle.Name = "btnMarkaGüncelle";
            this.btnMarkaGüncelle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMarkaGüncelle.OnDisabledState.BorderRadius = 30;
            this.btnMarkaGüncelle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMarkaGüncelle.OnDisabledState.BorderThickness = 1;
            this.btnMarkaGüncelle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMarkaGüncelle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMarkaGüncelle.OnDisabledState.IconLeftImage = null;
            this.btnMarkaGüncelle.OnDisabledState.IconRightImage = null;
            this.btnMarkaGüncelle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnMarkaGüncelle.onHoverState.BorderRadius = 30;
            this.btnMarkaGüncelle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMarkaGüncelle.onHoverState.BorderThickness = 1;
            this.btnMarkaGüncelle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnMarkaGüncelle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnMarkaGüncelle.onHoverState.IconLeftImage = null;
            this.btnMarkaGüncelle.onHoverState.IconRightImage = null;
            this.btnMarkaGüncelle.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnMarkaGüncelle.OnIdleState.BorderRadius = 30;
            this.btnMarkaGüncelle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMarkaGüncelle.OnIdleState.BorderThickness = 1;
            this.btnMarkaGüncelle.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnMarkaGüncelle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMarkaGüncelle.OnIdleState.IconLeftImage = null;
            this.btnMarkaGüncelle.OnIdleState.IconRightImage = null;
            this.btnMarkaGüncelle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnMarkaGüncelle.OnPressedState.BorderRadius = 30;
            this.btnMarkaGüncelle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMarkaGüncelle.OnPressedState.BorderThickness = 1;
            this.btnMarkaGüncelle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnMarkaGüncelle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMarkaGüncelle.OnPressedState.IconLeftImage = null;
            this.btnMarkaGüncelle.OnPressedState.IconRightImage = null;
            this.btnMarkaGüncelle.Size = new System.Drawing.Size(162, 39);
            this.btnMarkaGüncelle.TabIndex = 11;
            this.btnMarkaGüncelle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMarkaGüncelle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMarkaGüncelle.TextMarginLeft = 0;
            this.btnMarkaGüncelle.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMarkaGüncelle.UseDefaultRadiusAndThickness = true;
            this.btnMarkaGüncelle.Click += new System.EventHandler(this.btnMarkaGüncelle_Click);
            // 
            // btnGüncelle
            // 
            this.btnGüncelle.AllowAnimations = true;
            this.btnGüncelle.AllowMouseEffects = true;
            this.btnGüncelle.AllowToggling = false;
            this.btnGüncelle.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnGüncelle.AnimationSpeed = 200;
            this.btnGüncelle.AutoGenerateColors = false;
            this.btnGüncelle.AutoRoundBorders = false;
            this.btnGüncelle.AutoSizeLeftIcon = true;
            this.btnGüncelle.AutoSizeRightIcon = true;
            this.btnGüncelle.BackColor = System.Drawing.Color.Transparent;
            this.btnGüncelle.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnGüncelle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGüncelle.BackgroundImage")));
            this.btnGüncelle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGüncelle.ButtonText = "Güncelle";
            this.btnGüncelle.ButtonTextMarginLeft = 0;
            this.btnGüncelle.ColorContrastOnClick = 45;
            this.btnGüncelle.ColorContrastOnHover = 45;
            this.btnGüncelle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnGüncelle.CustomizableEdges = borderEdges3;
            this.btnGüncelle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGüncelle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGüncelle.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnGüncelle.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnGüncelle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGüncelle.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGüncelle.ForeColor = System.Drawing.Color.White;
            this.btnGüncelle.IconLeft = null;
            this.btnGüncelle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGüncelle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGüncelle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGüncelle.IconMarginLeft = 11;
            this.btnGüncelle.IconPadding = 10;
            this.btnGüncelle.IconRight = null;
            this.btnGüncelle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGüncelle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGüncelle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGüncelle.IconSize = 25;
            this.btnGüncelle.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnGüncelle.IdleBorderRadius = 0;
            this.btnGüncelle.IdleBorderThickness = 0;
            this.btnGüncelle.IdleFillColor = System.Drawing.Color.Empty;
            this.btnGüncelle.IdleIconLeftImage = null;
            this.btnGüncelle.IdleIconRightImage = null;
            this.btnGüncelle.IndicateFocus = false;
            this.btnGüncelle.Location = new System.Drawing.Point(193, 505);
            this.btnGüncelle.Name = "btnGüncelle";
            this.btnGüncelle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGüncelle.OnDisabledState.BorderRadius = 30;
            this.btnGüncelle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGüncelle.OnDisabledState.BorderThickness = 1;
            this.btnGüncelle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGüncelle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGüncelle.OnDisabledState.IconLeftImage = null;
            this.btnGüncelle.OnDisabledState.IconRightImage = null;
            this.btnGüncelle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnGüncelle.onHoverState.BorderRadius = 30;
            this.btnGüncelle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGüncelle.onHoverState.BorderThickness = 1;
            this.btnGüncelle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnGüncelle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGüncelle.onHoverState.IconLeftImage = null;
            this.btnGüncelle.onHoverState.IconRightImage = null;
            this.btnGüncelle.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnGüncelle.OnIdleState.BorderRadius = 30;
            this.btnGüncelle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGüncelle.OnIdleState.BorderThickness = 1;
            this.btnGüncelle.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnGüncelle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGüncelle.OnIdleState.IconLeftImage = null;
            this.btnGüncelle.OnIdleState.IconRightImage = null;
            this.btnGüncelle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnGüncelle.OnPressedState.BorderRadius = 30;
            this.btnGüncelle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGüncelle.OnPressedState.BorderThickness = 1;
            this.btnGüncelle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnGüncelle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGüncelle.OnPressedState.IconLeftImage = null;
            this.btnGüncelle.OnPressedState.IconRightImage = null;
            this.btnGüncelle.Size = new System.Drawing.Size(150, 39);
            this.btnGüncelle.TabIndex = 8;
            this.btnGüncelle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGüncelle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGüncelle.TextMarginLeft = 0;
            this.btnGüncelle.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGüncelle.UseDefaultRadiusAndThickness = true;
            this.btnGüncelle.Click += new System.EventHandler(this.btnGüncelle_Click);
            // 
            // SatışFiyatıtxt
            // 
            this.SatışFiyatıtxt.AcceptsReturn = false;
            this.SatışFiyatıtxt.AcceptsTab = false;
            this.SatışFiyatıtxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.SatışFiyatıtxt.AnimationSpeed = 200;
            this.SatışFiyatıtxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.SatışFiyatıtxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.SatışFiyatıtxt.AutoSizeHeight = true;
            this.SatışFiyatıtxt.BackColor = System.Drawing.Color.Transparent;
            this.SatışFiyatıtxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SatışFiyatıtxt.BackgroundImage")));
            this.SatışFiyatıtxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.SatışFiyatıtxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SatışFiyatıtxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SatışFiyatıtxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.SatışFiyatıtxt.BorderRadius = 10;
            this.SatışFiyatıtxt.BorderThickness = 1;
            this.SatışFiyatıtxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.SatışFiyatıtxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.SatışFiyatıtxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.SatışFiyatıtxt.DefaultText = "";
            this.SatışFiyatıtxt.FillColor = System.Drawing.Color.White;
            this.SatışFiyatıtxt.ForeColor = System.Drawing.Color.Black;
            this.SatışFiyatıtxt.HideSelection = true;
            this.SatışFiyatıtxt.IconLeft = null;
            this.SatışFiyatıtxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.SatışFiyatıtxt.IconPadding = 12;
            this.SatışFiyatıtxt.IconRight = null;
            this.SatışFiyatıtxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.SatışFiyatıtxt.Lines = new string[0];
            this.SatışFiyatıtxt.Location = new System.Drawing.Point(133, 446);
            this.SatışFiyatıtxt.MaxLength = 32767;
            this.SatışFiyatıtxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.SatışFiyatıtxt.Modified = false;
            this.SatışFiyatıtxt.Multiline = false;
            this.SatışFiyatıtxt.Name = "SatışFiyatıtxt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SatışFiyatıtxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.SatışFiyatıtxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SatışFiyatıtxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SatışFiyatıtxt.OnIdleState = stateProperties4;
            this.SatışFiyatıtxt.Padding = new System.Windows.Forms.Padding(3);
            this.SatışFiyatıtxt.PasswordChar = '\0';
            this.SatışFiyatıtxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.SatışFiyatıtxt.PlaceholderText = "";
            this.SatışFiyatıtxt.ReadOnly = false;
            this.SatışFiyatıtxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.SatışFiyatıtxt.SelectedText = "";
            this.SatışFiyatıtxt.SelectionLength = 0;
            this.SatışFiyatıtxt.SelectionStart = 0;
            this.SatışFiyatıtxt.ShortcutsEnabled = true;
            this.SatışFiyatıtxt.Size = new System.Drawing.Size(210, 39);
            this.SatışFiyatıtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.SatışFiyatıtxt.TabIndex = 7;
            this.SatışFiyatıtxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.SatışFiyatıtxt.TextMarginBottom = 0;
            this.SatışFiyatıtxt.TextMarginLeft = 3;
            this.SatışFiyatıtxt.TextMarginTop = 1;
            this.SatışFiyatıtxt.TextPlaceholder = "";
            this.SatışFiyatıtxt.UseSystemPasswordChar = false;
            this.SatışFiyatıtxt.WordWrap = true;
            // 
            // AlışFiyatıtxt
            // 
            this.AlışFiyatıtxt.AcceptsReturn = false;
            this.AlışFiyatıtxt.AcceptsTab = false;
            this.AlışFiyatıtxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.AlışFiyatıtxt.AnimationSpeed = 200;
            this.AlışFiyatıtxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AlışFiyatıtxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AlışFiyatıtxt.AutoSizeHeight = true;
            this.AlışFiyatıtxt.BackColor = System.Drawing.Color.Transparent;
            this.AlışFiyatıtxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AlışFiyatıtxt.BackgroundImage")));
            this.AlışFiyatıtxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AlışFiyatıtxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AlışFiyatıtxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AlışFiyatıtxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.AlışFiyatıtxt.BorderRadius = 10;
            this.AlışFiyatıtxt.BorderThickness = 1;
            this.AlışFiyatıtxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AlışFiyatıtxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AlışFiyatıtxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AlışFiyatıtxt.DefaultText = "";
            this.AlışFiyatıtxt.FillColor = System.Drawing.Color.White;
            this.AlışFiyatıtxt.ForeColor = System.Drawing.Color.Black;
            this.AlışFiyatıtxt.HideSelection = true;
            this.AlışFiyatıtxt.IconLeft = null;
            this.AlışFiyatıtxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AlışFiyatıtxt.IconPadding = 12;
            this.AlışFiyatıtxt.IconRight = null;
            this.AlışFiyatıtxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AlışFiyatıtxt.Lines = new string[0];
            this.AlışFiyatıtxt.Location = new System.Drawing.Point(133, 383);
            this.AlışFiyatıtxt.MaxLength = 32767;
            this.AlışFiyatıtxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.AlışFiyatıtxt.Modified = false;
            this.AlışFiyatıtxt.Multiline = false;
            this.AlışFiyatıtxt.Name = "AlışFiyatıtxt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AlışFiyatıtxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AlışFiyatıtxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AlışFiyatıtxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AlışFiyatıtxt.OnIdleState = stateProperties8;
            this.AlışFiyatıtxt.Padding = new System.Windows.Forms.Padding(3);
            this.AlışFiyatıtxt.PasswordChar = '\0';
            this.AlışFiyatıtxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AlışFiyatıtxt.PlaceholderText = "";
            this.AlışFiyatıtxt.ReadOnly = false;
            this.AlışFiyatıtxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AlışFiyatıtxt.SelectedText = "";
            this.AlışFiyatıtxt.SelectionLength = 0;
            this.AlışFiyatıtxt.SelectionStart = 0;
            this.AlışFiyatıtxt.ShortcutsEnabled = true;
            this.AlışFiyatıtxt.Size = new System.Drawing.Size(210, 39);
            this.AlışFiyatıtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AlışFiyatıtxt.TabIndex = 6;
            this.AlışFiyatıtxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AlışFiyatıtxt.TextMarginBottom = 0;
            this.AlışFiyatıtxt.TextMarginLeft = 3;
            this.AlışFiyatıtxt.TextMarginTop = 1;
            this.AlışFiyatıtxt.TextPlaceholder = "";
            this.AlışFiyatıtxt.UseSystemPasswordChar = false;
            this.AlışFiyatıtxt.WordWrap = true;
            // 
            // textBox1
            // 
            this.textBox1.AcceptsReturn = false;
            this.textBox1.AcceptsTab = false;
            this.textBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.textBox1.AnimationSpeed = 200;
            this.textBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBox1.AutoSizeHeight = true;
            this.textBox1.BackColor = System.Drawing.Color.Transparent;
            this.textBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBox1.BackgroundImage")));
            this.textBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBox1.BorderRadius = 10;
            this.textBox1.BorderThickness = 1;
            this.textBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textBox1.DefaultText = "";
            this.textBox1.FillColor = System.Drawing.Color.White;
            this.textBox1.HideSelection = true;
            this.textBox1.IconLeft = null;
            this.textBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBox1.IconPadding = 12;
            this.textBox1.IconRight = null;
            this.textBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBox1.Lines = new string[0];
            this.textBox1.Location = new System.Drawing.Point(1046, 22);
            this.textBox1.MaxLength = 32767;
            this.textBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBox1.Modified = false;
            this.textBox1.Multiline = false;
            this.textBox1.Name = "textBox1";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBox1.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBox1.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBox1.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBox1.OnIdleState = stateProperties12;
            this.textBox1.Padding = new System.Windows.Forms.Padding(3);
            this.textBox1.PasswordChar = '\0';
            this.textBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textBox1.PlaceholderText = "";
            this.textBox1.ReadOnly = false;
            this.textBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBox1.SelectedText = "";
            this.textBox1.SelectionLength = 0;
            this.textBox1.SelectionStart = 0;
            this.textBox1.ShortcutsEnabled = true;
            this.textBox1.Size = new System.Drawing.Size(210, 39);
            this.textBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textBox1.TabIndex = 14;
            this.textBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBox1.TextMarginBottom = 0;
            this.textBox1.TextMarginLeft = 3;
            this.textBox1.TextMarginTop = 1;
            this.textBox1.TextPlaceholder = "";
            this.textBox1.UseSystemPasswordChar = false;
            this.textBox1.WordWrap = true;
            this.textBox1.TextChange += new System.EventHandler(this.textBox1_TextChanged);
            // 
            // Miktarıtxt
            // 
            this.Miktarıtxt.AcceptsReturn = false;
            this.Miktarıtxt.AcceptsTab = false;
            this.Miktarıtxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Miktarıtxt.AnimationSpeed = 200;
            this.Miktarıtxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Miktarıtxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Miktarıtxt.AutoSizeHeight = true;
            this.Miktarıtxt.BackColor = System.Drawing.Color.Transparent;
            this.Miktarıtxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Miktarıtxt.BackgroundImage")));
            this.Miktarıtxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Miktarıtxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Miktarıtxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Miktarıtxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.Miktarıtxt.BorderRadius = 10;
            this.Miktarıtxt.BorderThickness = 1;
            this.Miktarıtxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Miktarıtxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Miktarıtxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Miktarıtxt.DefaultText = "";
            this.Miktarıtxt.FillColor = System.Drawing.Color.White;
            this.Miktarıtxt.ForeColor = System.Drawing.Color.Black;
            this.Miktarıtxt.HideSelection = true;
            this.Miktarıtxt.IconLeft = null;
            this.Miktarıtxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Miktarıtxt.IconPadding = 12;
            this.Miktarıtxt.IconRight = null;
            this.Miktarıtxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Miktarıtxt.Lines = new string[0];
            this.Miktarıtxt.Location = new System.Drawing.Point(133, 320);
            this.Miktarıtxt.MaxLength = 32767;
            this.Miktarıtxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.Miktarıtxt.Modified = false;
            this.Miktarıtxt.Multiline = false;
            this.Miktarıtxt.Name = "Miktarıtxt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Miktarıtxt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Miktarıtxt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Miktarıtxt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Miktarıtxt.OnIdleState = stateProperties16;
            this.Miktarıtxt.Padding = new System.Windows.Forms.Padding(3);
            this.Miktarıtxt.PasswordChar = '\0';
            this.Miktarıtxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Miktarıtxt.PlaceholderText = "";
            this.Miktarıtxt.ReadOnly = false;
            this.Miktarıtxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Miktarıtxt.SelectedText = "";
            this.Miktarıtxt.SelectionLength = 0;
            this.Miktarıtxt.SelectionStart = 0;
            this.Miktarıtxt.ShortcutsEnabled = true;
            this.Miktarıtxt.Size = new System.Drawing.Size(210, 39);
            this.Miktarıtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Miktarıtxt.TabIndex = 5;
            this.Miktarıtxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Miktarıtxt.TextMarginBottom = 0;
            this.Miktarıtxt.TextMarginLeft = 3;
            this.Miktarıtxt.TextMarginTop = 1;
            this.Miktarıtxt.TextPlaceholder = "";
            this.Miktarıtxt.UseSystemPasswordChar = false;
            this.Miktarıtxt.WordWrap = true;
            // 
            // ÜrünAdıtxt
            // 
            this.ÜrünAdıtxt.AcceptsReturn = false;
            this.ÜrünAdıtxt.AcceptsTab = false;
            this.ÜrünAdıtxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.ÜrünAdıtxt.AnimationSpeed = 200;
            this.ÜrünAdıtxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ÜrünAdıtxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ÜrünAdıtxt.AutoSizeHeight = true;
            this.ÜrünAdıtxt.BackColor = System.Drawing.Color.Transparent;
            this.ÜrünAdıtxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ÜrünAdıtxt.BackgroundImage")));
            this.ÜrünAdıtxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ÜrünAdıtxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ÜrünAdıtxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ÜrünAdıtxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ÜrünAdıtxt.BorderRadius = 10;
            this.ÜrünAdıtxt.BorderThickness = 1;
            this.ÜrünAdıtxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ÜrünAdıtxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ÜrünAdıtxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ÜrünAdıtxt.DefaultText = "";
            this.ÜrünAdıtxt.FillColor = System.Drawing.Color.White;
            this.ÜrünAdıtxt.ForeColor = System.Drawing.Color.Black;
            this.ÜrünAdıtxt.HideSelection = true;
            this.ÜrünAdıtxt.IconLeft = null;
            this.ÜrünAdıtxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ÜrünAdıtxt.IconPadding = 12;
            this.ÜrünAdıtxt.IconRight = null;
            this.ÜrünAdıtxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ÜrünAdıtxt.Lines = new string[0];
            this.ÜrünAdıtxt.Location = new System.Drawing.Point(133, 258);
            this.ÜrünAdıtxt.MaxLength = 32767;
            this.ÜrünAdıtxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ÜrünAdıtxt.Modified = false;
            this.ÜrünAdıtxt.Multiline = false;
            this.ÜrünAdıtxt.Name = "ÜrünAdıtxt";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ÜrünAdıtxt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ÜrünAdıtxt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ÜrünAdıtxt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ÜrünAdıtxt.OnIdleState = stateProperties20;
            this.ÜrünAdıtxt.Padding = new System.Windows.Forms.Padding(3);
            this.ÜrünAdıtxt.PasswordChar = '\0';
            this.ÜrünAdıtxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ÜrünAdıtxt.PlaceholderText = "";
            this.ÜrünAdıtxt.ReadOnly = false;
            this.ÜrünAdıtxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ÜrünAdıtxt.SelectedText = "";
            this.ÜrünAdıtxt.SelectionLength = 0;
            this.ÜrünAdıtxt.SelectionStart = 0;
            this.ÜrünAdıtxt.ShortcutsEnabled = true;
            this.ÜrünAdıtxt.Size = new System.Drawing.Size(210, 39);
            this.ÜrünAdıtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ÜrünAdıtxt.TabIndex = 4;
            this.ÜrünAdıtxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ÜrünAdıtxt.TextMarginBottom = 0;
            this.ÜrünAdıtxt.TextMarginLeft = 3;
            this.ÜrünAdıtxt.TextMarginTop = 1;
            this.ÜrünAdıtxt.TextPlaceholder = "";
            this.ÜrünAdıtxt.UseSystemPasswordChar = false;
            this.ÜrünAdıtxt.WordWrap = true;
            // 
            // Markatxt
            // 
            this.Markatxt.AcceptsReturn = false;
            this.Markatxt.AcceptsTab = false;
            this.Markatxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Markatxt.AnimationSpeed = 200;
            this.Markatxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Markatxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Markatxt.AutoSizeHeight = true;
            this.Markatxt.BackColor = System.Drawing.Color.Transparent;
            this.Markatxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Markatxt.BackgroundImage")));
            this.Markatxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Markatxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Markatxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Markatxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.Markatxt.BorderRadius = 10;
            this.Markatxt.BorderThickness = 1;
            this.Markatxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Markatxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Markatxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Markatxt.DefaultText = "";
            this.Markatxt.FillColor = System.Drawing.Color.White;
            this.Markatxt.ForeColor = System.Drawing.Color.Black;
            this.Markatxt.HideSelection = true;
            this.Markatxt.IconLeft = null;
            this.Markatxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Markatxt.IconPadding = 12;
            this.Markatxt.IconRight = null;
            this.Markatxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Markatxt.Lines = new string[0];
            this.Markatxt.Location = new System.Drawing.Point(133, 195);
            this.Markatxt.MaxLength = 32767;
            this.Markatxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.Markatxt.Modified = false;
            this.Markatxt.Multiline = false;
            this.Markatxt.Name = "Markatxt";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Markatxt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Markatxt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Markatxt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Markatxt.OnIdleState = stateProperties24;
            this.Markatxt.Padding = new System.Windows.Forms.Padding(3);
            this.Markatxt.PasswordChar = '\0';
            this.Markatxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Markatxt.PlaceholderText = "";
            this.Markatxt.ReadOnly = false;
            this.Markatxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Markatxt.SelectedText = "";
            this.Markatxt.SelectionLength = 0;
            this.Markatxt.SelectionStart = 0;
            this.Markatxt.ShortcutsEnabled = true;
            this.Markatxt.Size = new System.Drawing.Size(210, 39);
            this.Markatxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Markatxt.TabIndex = 3;
            this.Markatxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Markatxt.TextMarginBottom = 0;
            this.Markatxt.TextMarginLeft = 3;
            this.Markatxt.TextMarginTop = 1;
            this.Markatxt.TextPlaceholder = "";
            this.Markatxt.UseSystemPasswordChar = false;
            this.Markatxt.WordWrap = true;
            // 
            // Kategoritxt
            // 
            this.Kategoritxt.AcceptsReturn = false;
            this.Kategoritxt.AcceptsTab = false;
            this.Kategoritxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Kategoritxt.AnimationSpeed = 200;
            this.Kategoritxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Kategoritxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Kategoritxt.AutoSizeHeight = true;
            this.Kategoritxt.BackColor = System.Drawing.Color.Transparent;
            this.Kategoritxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Kategoritxt.BackgroundImage")));
            this.Kategoritxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Kategoritxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Kategoritxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Kategoritxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.Kategoritxt.BorderRadius = 10;
            this.Kategoritxt.BorderThickness = 1;
            this.Kategoritxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Kategoritxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Kategoritxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Kategoritxt.DefaultText = "";
            this.Kategoritxt.FillColor = System.Drawing.Color.White;
            this.Kategoritxt.ForeColor = System.Drawing.Color.Black;
            this.Kategoritxt.HideSelection = true;
            this.Kategoritxt.IconLeft = null;
            this.Kategoritxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Kategoritxt.IconPadding = 12;
            this.Kategoritxt.IconRight = null;
            this.Kategoritxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Kategoritxt.Lines = new string[0];
            this.Kategoritxt.Location = new System.Drawing.Point(133, 133);
            this.Kategoritxt.MaxLength = 32767;
            this.Kategoritxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.Kategoritxt.Modified = false;
            this.Kategoritxt.Multiline = false;
            this.Kategoritxt.Name = "Kategoritxt";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Kategoritxt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Kategoritxt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Kategoritxt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Kategoritxt.OnIdleState = stateProperties28;
            this.Kategoritxt.Padding = new System.Windows.Forms.Padding(3);
            this.Kategoritxt.PasswordChar = '\0';
            this.Kategoritxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Kategoritxt.PlaceholderText = "";
            this.Kategoritxt.ReadOnly = false;
            this.Kategoritxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Kategoritxt.SelectedText = "";
            this.Kategoritxt.SelectionLength = 0;
            this.Kategoritxt.SelectionStart = 0;
            this.Kategoritxt.ShortcutsEnabled = true;
            this.Kategoritxt.Size = new System.Drawing.Size(210, 39);
            this.Kategoritxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Kategoritxt.TabIndex = 2;
            this.Kategoritxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Kategoritxt.TextMarginBottom = 0;
            this.Kategoritxt.TextMarginLeft = 3;
            this.Kategoritxt.TextMarginTop = 1;
            this.Kategoritxt.TextPlaceholder = "";
            this.Kategoritxt.UseSystemPasswordChar = false;
            this.Kategoritxt.WordWrap = true;
            // 
            // BarkodNotxt
            // 
            this.BarkodNotxt.AcceptsReturn = false;
            this.BarkodNotxt.AcceptsTab = false;
            this.BarkodNotxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.BarkodNotxt.AnimationSpeed = 200;
            this.BarkodNotxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.BarkodNotxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.BarkodNotxt.AutoSizeHeight = true;
            this.BarkodNotxt.BackColor = System.Drawing.Color.Transparent;
            this.BarkodNotxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BarkodNotxt.BackgroundImage")));
            this.BarkodNotxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.BarkodNotxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BarkodNotxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BarkodNotxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.BarkodNotxt.BorderRadius = 10;
            this.BarkodNotxt.BorderThickness = 1;
            this.BarkodNotxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.BarkodNotxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.BarkodNotxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.BarkodNotxt.DefaultText = "";
            this.BarkodNotxt.FillColor = System.Drawing.Color.White;
            this.BarkodNotxt.ForeColor = System.Drawing.Color.Black;
            this.BarkodNotxt.HideSelection = true;
            this.BarkodNotxt.IconLeft = null;
            this.BarkodNotxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.BarkodNotxt.IconPadding = 12;
            this.BarkodNotxt.IconRight = null;
            this.BarkodNotxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.BarkodNotxt.Lines = new string[0];
            this.BarkodNotxt.Location = new System.Drawing.Point(133, 71);
            this.BarkodNotxt.MaxLength = 32767;
            this.BarkodNotxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.BarkodNotxt.Modified = false;
            this.BarkodNotxt.Multiline = false;
            this.BarkodNotxt.Name = "BarkodNotxt";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.BarkodNotxt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.BarkodNotxt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.BarkodNotxt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Black;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.BarkodNotxt.OnIdleState = stateProperties32;
            this.BarkodNotxt.Padding = new System.Windows.Forms.Padding(3);
            this.BarkodNotxt.PasswordChar = '\0';
            this.BarkodNotxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.BarkodNotxt.PlaceholderText = "";
            this.BarkodNotxt.ReadOnly = false;
            this.BarkodNotxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.BarkodNotxt.SelectedText = "";
            this.BarkodNotxt.SelectionLength = 0;
            this.BarkodNotxt.SelectionStart = 0;
            this.BarkodNotxt.ShortcutsEnabled = true;
            this.BarkodNotxt.Size = new System.Drawing.Size(210, 39);
            this.BarkodNotxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.BarkodNotxt.TabIndex = 1;
            this.BarkodNotxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.BarkodNotxt.TextMarginBottom = 0;
            this.BarkodNotxt.TextMarginLeft = 3;
            this.BarkodNotxt.TextMarginTop = 1;
            this.BarkodNotxt.TextPlaceholder = "";
            this.BarkodNotxt.UseSystemPasswordChar = false;
            this.BarkodNotxt.WordWrap = true;
            // 
            // label8
            // 
            this.label8.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label8.Location = new System.Drawing.Point(22, 455);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(100, 18);
            this.label8.TabIndex = 40;
            this.label8.Text = "Satıs Fiyatı:";
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label1.Location = new System.Drawing.Point(848, 30);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(192, 18);
            this.label1.TabIndex = 43;
            this.label1.Text = "Barkod No\'ya göre ara:";
            // 
            // label9
            // 
            this.label9.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label9.Location = new System.Drawing.Point(22, 392);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(89, 18);
            this.label9.TabIndex = 41;
            this.label9.Text = "Alıs Fiyatı:";
            // 
            // label10
            // 
            this.label10.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label10.Location = new System.Drawing.Point(22, 329);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(66, 18);
            this.label10.TabIndex = 42;
            this.label10.Text = "Miktarı:";
            // 
            // label11
            // 
            this.label11.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label11.Location = new System.Drawing.Point(22, 267);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(82, 18);
            this.label11.TabIndex = 44;
            this.label11.Text = "Ürün Adı:";
            // 
            // label12
            // 
            this.label12.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label12.Location = new System.Drawing.Point(22, 203);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(62, 18);
            this.label12.TabIndex = 45;
            this.label12.Text = "Marka:";
            // 
            // label13
            // 
            this.label13.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label13.Location = new System.Drawing.Point(22, 141);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(82, 18);
            this.label13.TabIndex = 46;
            this.label13.Text = "Kategori:";
            // 
            // label14
            // 
            this.label14.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Arial Rounded MT Bold", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label14.Location = new System.Drawing.Point(22, 79);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(97, 18);
            this.label14.TabIndex = 47;
            this.label14.Text = "Barkod No:";
            // 
            // btnYazdir
            // 
            this.btnYazdir.AllowAnimations = true;
            this.btnYazdir.AllowMouseEffects = true;
            this.btnYazdir.AllowToggling = false;
            this.btnYazdir.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnYazdir.AnimationSpeed = 200;
            this.btnYazdir.AutoGenerateColors = false;
            this.btnYazdir.AutoRoundBorders = false;
            this.btnYazdir.AutoSizeLeftIcon = true;
            this.btnYazdir.AutoSizeRightIcon = true;
            this.btnYazdir.BackColor = System.Drawing.Color.Transparent;
            this.btnYazdir.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnYazdir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnYazdir.BackgroundImage")));
            this.btnYazdir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.ButtonText = "Yazdır";
            this.btnYazdir.ButtonTextMarginLeft = 0;
            this.btnYazdir.ColorContrastOnClick = 45;
            this.btnYazdir.ColorContrastOnHover = 45;
            this.btnYazdir.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnYazdir.CustomizableEdges = borderEdges4;
            this.btnYazdir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnYazdir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnYazdir.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnYazdir.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnYazdir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnYazdir.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnYazdir.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.IconLeft = null;
            this.btnYazdir.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnYazdir.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnYazdir.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnYazdir.IconMarginLeft = 11;
            this.btnYazdir.IconPadding = 10;
            this.btnYazdir.IconRight = null;
            this.btnYazdir.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnYazdir.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnYazdir.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnYazdir.IconSize = 25;
            this.btnYazdir.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnYazdir.IdleBorderRadius = 0;
            this.btnYazdir.IdleBorderThickness = 0;
            this.btnYazdir.IdleFillColor = System.Drawing.Color.Empty;
            this.btnYazdir.IdleIconLeftImage = null;
            this.btnYazdir.IdleIconRightImage = null;
            this.btnYazdir.IndicateFocus = false;
            this.btnYazdir.Location = new System.Drawing.Point(1134, 537);
            this.btnYazdir.Name = "btnYazdir";
            this.btnYazdir.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnYazdir.OnDisabledState.BorderRadius = 23;
            this.btnYazdir.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.OnDisabledState.BorderThickness = 1;
            this.btnYazdir.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnYazdir.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnYazdir.OnDisabledState.IconLeftImage = null;
            this.btnYazdir.OnDisabledState.IconRightImage = null;
            this.btnYazdir.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnYazdir.onHoverState.BorderRadius = 23;
            this.btnYazdir.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.onHoverState.BorderThickness = 1;
            this.btnYazdir.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(133)))), ((int)(((byte)(0)))));
            this.btnYazdir.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.onHoverState.IconLeftImage = null;
            this.btnYazdir.onHoverState.IconRightImage = null;
            this.btnYazdir.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnYazdir.OnIdleState.BorderRadius = 23;
            this.btnYazdir.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.OnIdleState.BorderThickness = 1;
            this.btnYazdir.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(50)))));
            this.btnYazdir.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.OnIdleState.IconLeftImage = null;
            this.btnYazdir.OnIdleState.IconRightImage = null;
            this.btnYazdir.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnYazdir.OnPressedState.BorderRadius = 23;
            this.btnYazdir.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYazdir.OnPressedState.BorderThickness = 1;
            this.btnYazdir.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnYazdir.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnYazdir.OnPressedState.IconLeftImage = null;
            this.btnYazdir.OnPressedState.IconRightImage = null;
            this.btnYazdir.Size = new System.Drawing.Size(122, 32);
            this.btnYazdir.TabIndex = 13;
            this.btnYazdir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnYazdir.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnYazdir.TextMarginLeft = 0;
            this.btnYazdir.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnYazdir.UseDefaultRadiusAndThickness = true;
            this.btnYazdir.Click += new System.EventHandler(this.btnYazdir_Click);
            // 
            // FormUrunListele
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(33)))), ((int)(((byte)(74)))));
            this.ClientSize = new System.Drawing.Size(1268, 619);
            this.Controls.Add(this.comboMarka);
            this.Controls.Add(this.comboKategori);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.btnYazdir);
            this.Controls.Add(this.btnSil);
            this.Controls.Add(this.btnMarkaGüncelle);
            this.Controls.Add(this.btnGüncelle);
            this.Controls.Add(this.SatışFiyatıtxt);
            this.Controls.Add(this.AlışFiyatıtxt);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.Miktarıtxt);
            this.Controls.Add(this.ÜrünAdıtxt);
            this.Controls.Add(this.Markatxt);
            this.Controls.Add(this.Kategoritxt);
            this.Controls.Add(this.BarkodNotxt);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label14);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormUrunListele";
            this.Text = "FormUrunListele";
            this.Load += new System.EventHandler(this.FormUrunListele_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2ComboBox comboMarka;
        private Guna.UI2.WinForms.Guna2ComboBox comboKategori;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSil;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMarkaGüncelle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGüncelle;
        private Bunifu.UI.WinForms.BunifuTextBox SatışFiyatıtxt;
        private Bunifu.UI.WinForms.BunifuTextBox AlışFiyatıtxt;
        private Bunifu.UI.WinForms.BunifuTextBox textBox1;
        private Bunifu.UI.WinForms.BunifuTextBox Miktarıtxt;
        private Bunifu.UI.WinForms.BunifuTextBox ÜrünAdıtxt;
        private Bunifu.UI.WinForms.BunifuTextBox Markatxt;
        private Bunifu.UI.WinForms.BunifuTextBox Kategoritxt;
        private Bunifu.UI.WinForms.BunifuTextBox BarkodNotxt;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnYazdir;
        private System.Drawing.Printing.PrintDocument printDocument1;
    }
}